#!/usr/bin/env node

const glob = require('glob');
const Mocha = require('mocha');

// pattern for test files
const testFiles = 'app/{,!(node_modules)/**/}*.spec.js';

// mocha options
const opts = {};

glob(testFiles, function (err, files) {
  if (err) return process.exit(1);
  const mocha = new Mocha(opts);
  files.forEach(file => mocha.addFile(file));
  return mocha.run(errCount => process.exit(errCount));
});
