module.exports = {
  NEW_FILE: 'NEW_FILE',
  OPEN_FILE: 'OPEN_FILE',
  SAVE_FILE: 'SAVE_FILE',
  CLOSE_FILE: 'CLOSE_FILE',
  REQUEST_TERMINATION: 'REQUEST_TERMINATION',
  CONFIRM_TERMINATION: 'CONFIRM_TERMINATION'
};
