module.exports = {
  NEW_FILE: 'NEW_FILE',
  OPEN_FILE: 'OPEN_FILE',
  SAVE_FILE: 'SAVE_FILE',
  CLOSE_FILE: 'CLOSE_FILE',
  REQUEST_TERMINATION: 'REQUEST_TERMINATION',
  OPEN_MESSAGE_BOX: 'OPEN_MESSAGE_BOX',
  SHOW_MESSAGE: 'SHOW_MESSAGE'
};
